// Generalize skills to careerSkills
export const mappings = {
  // Keep existing mappings for tech-related careers
  ...{
    "react.js": "react",
    reactjs: "react",
    react: "react",
    "next.js": "nextjs",
    nextjs: "nextjs",
    next: "nextjs",
    // etc...
  },
  // Add mappings for various global careers
  accountant: "accounting",
  actuary: "finance",
  administrator: "administration",
  archaeologist: "archaeology",
  artist: "art",
  astronomer: "astronomy",
  banker: "finance",
  barber: "personal_care",
  biologist: "biology",
  bricklayer: "construction",
  bus_driver: "transportation",
  carpenter: "carpentry",
  cashier: "retail",
  chef: "culinary",
  chemist: "chemistry",
  civil_engineer: "engineering",
  cleaner: "maintenance",
  clerk: "clerical",
  coach: "sports",
  consultant: "consulting",
  content_creator: "media",
  copywriter: "writing",
  dentist: "dentistry",
  designer: "design",
  developer: "software_development",
  doctor: "medicine",
  economist: "economics",
  editor: "publishing",
  electrician: "electrician",
  engineer: "engineering",
  farmer: "agriculture",
  firefighter: "public_safety",
  flight_attendant: "aviation",
  florist: "floristry",
  geologist: "geology",
  graphic_designer: "design",
  hairdresser: "personal_care",
  hotel_manager: "hospitality",
  HR_specialist: "human_resources",
  journalist: "journalism",
  judge: "law",
  lawyer: "law",
  librarian: "library_science",
  machine_operator: "manufacturing",
  marketer: "marketing",
  mechanic: "mechanical",
  midwife: "midwifery",
  musician: "music",
  nurse: "nursing",
  nutritionist: "health",
  paramedic: "emergency_services",
  pharmacist: "pharmacy",
  photographer: "photography",
  pilot: "aviation",
  plumber: "plumbing",
  police_officer: "public_safety",
  politician: "government",
  professor: "academia",
  programmer: "software_development",
  psychologist: "psychology",
  receptionist: "administration",
  researcher: "research",
  retail_associate: "retail",
  scientist: "science",
  secretary: "clerical",
  security_guard: "security",
  social_worker: "social_work",
  software_engineer: "software_development",
  soldier: "military",
  statistician: "statistics",
  surgeon: "medicine",
  teacher: "education",
  technician: "technical",
  translator: "languages",
  truck_driver: "logistics",
  veterinarian: "veterinary_medicine",
  waiter: "hospitality",
  welder: "manufacturing",
  writer: "writing"
};

export const interviewCovers = [
  "/adobe.png",
  "/amazon.png",
  "/facebook.png",
  "/hospital.png",
  "/lawfirm.png",
  "/school.png",
  "/store.png",
  "/bank.png",
  "/techcompany.png",
  "/radio.png",
  "/marketing-agency.png",
  "/construction.png",
  "/airline.png",
  "/farm.png",
  "/studio.png",
];

export const dummyInterviews: Interview[] = [
  {
    id: "1",
    userId: "user1",
    role: "Frontend Developer",
    type: "Technical",
    careerSkills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    level: "Junior",
    questions: ["What is React?"],
    finalized: false,
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "2",
    userId: "user1",
    role: "Nurse",
    type: "Healthcare",
    careerSkills: ["Nursing", "Patient Care", "Vitals Monitoring"],
    level: "Intermediate",
    questions: ["How do you handle emergencies in the ER?"],
    finalized: false,
    createdAt: "2024-03-12T09:20:00Z",
  },
  {
    id: "3",
    userId: "user1",
    role: "Marketing Specialist",
    type: "Non-Technical",
    careerSkills: ["SEO", "Content Strategy", "Analytics"],
    level: "Senior",
    questions: ["How do you measure content performance?"],
    finalized: false,
    createdAt: "2024-03-10T14:05:00Z",
  },
  {
    id: "4",
    userId: "user2",
    role: "Teacher",
    type: "Education",
    careerSkills: ["Curriculum Development", "Student Engagement", "Assessment"],
    level: "Entry",
    questions: ["How do you manage a diverse classroom?"],
    finalized: false,
    createdAt: "2024-03-08T11:45:00Z",
  },
  {
    id: "5",
    userId: "user3",
    role: "Lawyer",
    type: "Legal",
    careerSkills: ["Legal Research", "Client Advocacy", "Contract Drafting"],
    level: "Mid",
    questions: ["Describe a case where you had to defend a difficult client."],
    finalized: false,
    createdAt: "2024-03-06T13:30:00Z",
  },
  {
    id: "6",
    userId: "user3",
    role: "Chef",
    type: "Culinary",
    careerSkills: ["Menu Design", "Food Safety", "Team Management"],
    level: "Senior",
    questions: ["Describe your approach to kitchen efficiency and team coordination."],
    finalized: false,
    createdAt: "2024-03-04T12:00:00Z",
  },
  {
    id: "7",
    userId: "user4",
    role: "Civil Engineer",
    type: "Engineering",
    careerSkills: ["Structural Design", "Project Management", "AutoCAD"],
    level: "Intermediate",
    questions: ["How do you ensure safety and compliance in construction projects?"],
    finalized: false,
    createdAt: "2024-03-01T10:30:00Z",
  }
];